I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script
    show screen judul_cerita
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen judul_cerita is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script
    show screen judul_cerita
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\ast.py", line 1974, in execute
    self.call("execute")
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\display\screen.py", line 1327, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen judul_cerita is not known.


Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090901
bOtTom_GEaR 6.9
Fri Nov  8 10:43:02 2024
