I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 76, in script call
    call rumahsakit
  File "game/script.rpy", line 76, in script call
    call rumahsakit
ScriptError: could not find label 'rumahsakit'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 76, in script call
    call rumahsakit
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\ast.py", line 1414, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 76, in script call
    call rumahsakit
  File "C:\Users\62813\renpy-8.3.2-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'rumahsakit'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090901
bOtTom_GEaR 6.9
Tue Nov  5 16:38:42 2024
